### ISSUE TITLE
Draft Year

### ISSUE THREAD

**Issue by thegarnetandgold** [jpf5046/NFL_Draft#1]
Pretty simple, powerful scraper. One thing I noticed offhand is that the draft year and round is missing. Could that be added?

**Comment by jpf5046** [comment]
Edited the code. Now includes draft year. Round should be included already "Rn" is the column header.

**Comment by jpf5046** [comment]
Let me know if the changes work.

**Comment by thegarnetandgold** [comment]
It worked!
